name: Android Artifact

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create unit test sources
        run: ./gradlew compileUnitTestSources
      - name: Run tests
        run: ./gradlew testDebugUnitTest
      - name: Build Release Apk
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v2
        with:
          name: pokedex-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk